# This is a basic workflow to help you get started with Actions

name: uppgift2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  envs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env: 
      message1: "Hello"
      message2: "World"
      

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: prints envs
        run: | 
          echo "message1: $message1"
          echo "message2: $message2"
          echo "$message1 $message2"
